name: SmallClassNr
version: "1.1.1"
license: "GPL-2.0-or-later"
date: 2023-04-19
description: |
    Library of groups with small class number

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.9"

www: https://stertooy.github.io/SmallClassNr
readme: README.md
packageinfo: https://stertooy.github.io/SmallClassNr/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stertooy/SmallClassNr/releases/download/v1.1.1/SmallClassNr-1.1.1.tar.gz

abstract: |
    Library of finite groups with small class number.

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    conjugacy, conjugacy class, class number.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter23</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>SmallClassNr, Library of groups with small class number,
             Version 1.1.1</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stertooy.github.io/SmallClassNr">https://stertooy.github.io/SmallClassNr</a></span>.
    </p>
    

bibtex: |
    @misc{ SmallClassNr1.1.1,
      author =           {Tertooy, S.},
      title =            {{SmallClassNr},  Library  of  groups  with small class
                          number, {V}ersion 1.1.1},
      month =            {Apr},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href        {https://stertooy.github.io/SmallClassNr}
                          {\texttt{https://stertooy.github.io/}\discretionary
                          {}{}{}\texttt{SmallClassNr}}},
      keywords =         {conjugacy; conjugacy class; class number},
      printedkey =       {Ter23}
    }

