name: SmallClassNr
version: "1.4.3"
license: "GPL-2.0-or-later"
date: 2025-11-13
description: |
    Library of finite groups with small class number

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.14"

www: https://stertooy.github.io/SmallClassNr
readme: README.md
packageinfo: https://stertooy.github.io/SmallClassNr/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stertooy/SmallClassNr/releases/download/v1.4.3/SmallClassNr-1.4.3.tar.gz

abstract: |
    Library of finite groups with small class number.

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    conjugacy, conjugacy class, class number.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter25</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>SmallClassNr, Library of finite groups with small class number,
             Version 1.4.3</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stertooy.github.io/SmallClassNr">https://stertooy.github.io/SmallClassNr</a></span>.
    </p>
    

bibtex: |
    @misc{ SmallClassNr,
      author =           {Tertooy, S.},
      title =            {{SmallClassNr},  {Library  of finite groups with small
                          class number}, {V}ersion 1.4.3},
      month =            {Nov},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://stertooy.github.io/SmallClassNr}
                          {\texttt{https://stertooy.github.io/}\discretionary
                          {}{}{}\texttt{SmallClassNr}}},
      keywords =         {conjugacy; conjugacy class; class number},
      printedkey =       {Ter25}
    }

