name: Test (package)
description: "Test package"
inputs:
  mode:
    required: false
    default: 'default'
  warnings-as-errors:
    required: false
    default: 'true'
  coverage:
    required: false
    default: 'false'
  codecov-token:
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: "Setup"
      uses: ./.github/actions/setup

    - name: "Run package tests"
      uses: gap-actions/run-pkg-tests@v4
      with:
        coverage: ${{ inputs.coverage }}
        mode: ${{ inputs.mode }}
        warnings-as-errors: ${{ inputs.warnings-as-errors }}

    - name: "Process coverage"
      if: ${{ inputs.coverage == 'true' }}
      uses: gap-actions/process-coverage@v3

    - name: "Upload coverage"
      if: ${{ inputs.coverage == 'true' }}
      uses: codecov/codecov-action@v6
      with:
        token: ${{ inputs.codecov-token }}
        fail_ci_if_error: true
