name: Test (GAP)
description: "Test GAP"
inputs:
  mode:
    default: 'default'
  warnings-as-errors:
    default: true
  complete:
    default: false

runs:
  using: "composite"
  steps:

    - name: "Setup"
      uses: ./.github/actions/setup

    - name: "Run GAP tests"
      uses: stertooy/run-gap-tests@v1
      with:
        complete: ${{ inputs.complete }}
        mode: ${{ inputs.mode }}
        warnings-as-errors: ${{ inputs.warnings-as-errors }}
