name: Lint
on:
  - push
  - pull_request
  - workflow_call
  - workflow_dispatch

jobs:

  lint:
    name: "Run gaplint (${{ matrix.rules }})"
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        include:
          - files: "*.g lib/**/*.g*"
            rules: "lib"
          - files: "examples/**/*.g*"
            rules: "examples"

    steps:
    
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: "Install gaplint"
        shell: bash
        run: pip install gaplint

      - name: "Run gaplint"
        shell: bash
        run: |
          shopt -s globstar extglob
          FILES="${{ matrix.files }}"
          gaplint $FILES --config-file=.github/gaplint-${{matrix.rules}}.yml
