name: Lint
on:
  - push
  - pull_request
  - workflow_call
  - workflow_dispatch

jobs:

  lint:
    name: "Run gaplint"
    runs-on: ubuntu-latest

    steps:
    
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: "Install gaplint"
        shell: bash
        run: pip install gaplint

      - name: "Run gaplint"
        shell: bash
        run: |
          shopt -s globstar extglob
          FILES="*.g !(doc)/**/*.g*"
          gaplint $FILES --config-file=.github/gaplint.yml
