name: Pre-release
on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: false

jobs:

  test-pkg:
    name: "Test package (version: ${{ matrix.gap-version }}, mode: ${{ matrix.mode }})"
    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-${{ matrix.mode == 'loadall' && 'full' || 'slim' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version: [ "4.14.0", "4.15.0", "4.15.1", "master" ]
        mode: [ "onlyneeded", "default", "loadall" ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Test package"
        uses: ./.github/actions/test-pkg
        with:
          mode: ${{ matrix.mode }}
          warnings-as-errors: ${{ matrix.mode != 'loadall' }}
          coverage: false

  test-gap:
    name: "Test GAP (version: ${{ matrix.gap-version }}, mode: ${{ matrix.mode }})"
    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-${{ matrix.mode == 'loadall' && 'full' || 'slim' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version: [ "4.14.0", "4.15.0", "4.15.1", "master" ]
        mode: [ "onlyneeded", "default", "loadall" ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Test package"
        uses: ./.github/actions/test-gap
        with:
          mode: ${{ matrix.mode }}
          warnings-as-errors: ${{ matrix.mode != 'loadall' }}
          complete: ${{ matrix.mode != 'loadall' }}

  deps:
    name: "Test dependency conflicts"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/stertooy/gda-image:master-slim

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: "Verify that tests do not depend on GAPDoc/PrimGrp/SmallGrp/TransGrp"
        shell: bash
        run: gap --bare -c 'TestPackage("SmallClassNr");'

  lint:
    name: "Run gaplint"
    uses: ./.github/workflows/lint.yml

  validate:
    name: "Run validation"
    uses: ./.github/workflows/validate.yml

  release-test:
    name: "Dry run of Release"
    uses: ./.github/workflows/release.yml
    with:
      dry-run: true
      force: ${{ inputs.force }}
