name: Release

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: true
      force:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Only create an archive containing the release instead of publishing it on GitHub"
        type: boolean
        required: false
        default: false
      force:
        description: "Allow overwriting an existing release, or making a release with an incorrect date"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release the GAP package"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/stertooy/gda-image:master-full

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: "Build manual"
        uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: true

      - name: "Copy changes"
        shell: bash
        id: changes
        run: |
          {
            echo 'RELEASE_NOTES<<EOF'
            echo "## Release notes"
            awk '/^## /{ if (seen++) exit; next } seen{ if (!printed && NF==0) next; printed=1; print }' CHANGELOG.md
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: "Make release"
        uses: gap-actions/release-pkg@v1
        with:
          dry-run: ${{ inputs.dry-run }}
          body-text: ${{ steps.changes.outputs.RELEASE_NOTES }} 
          force: ${{ inputs.force }}

      - name: "Update GitHub Pages"
        uses: gap-actions/update-gh-pages@v1
        if: ${{ !inputs.dry-run }}
