name: "Run GAP tests"

on:
  - workflow_dispatch

jobs:
  test:
    name: "Test on GAP-${{ matrix.gap-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version: [ "master", "4.15.0-beta1", "4.14.0" ]

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-slim

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Run GAP tests"
        uses: stertooy/run-gap-tests@v1
        with:
          complete: true
