name: Run package compatibility tests

on:
  - workflow_dispatch

jobs:
  test-pkg:
    name: "Test package with GAP-${{ matrix.gap-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version: [ "master", "4.15.0", "4.14.0" ]

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-full

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Run package tests"
        uses: gap-actions/run-pkg-tests@v4
        with:
          mode: 'loadall'
          warnings-as-errors: false
          coverage: false

  test-gap:
    name: "Test GAP-${{ matrix.gap-version }} with package"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version: [ "master", "4.15.0", "4.14.0" ]

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-full

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Run GAP tests"
        uses: stertooy/run-gap-tests@v1
        with:
          mode: 'loadall'
          warnings-as-errors: false

  test-additional:
    name: "Additional tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/stertooy/gda-image:master-slim

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Verify that tests do not depend on PrimGrp/SmallGrp/TransGrp"
        shell: bash
        run: gap --bare -c 'LoadPackage("GAPDoc");TestPackage("SmallClassNr");'
