name: Validate
on:
  - workflow_call
  - workflow_dispatch

jobs:

  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/stertooy/gda-image:master-slim

    steps:
    
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Validate CITATION.cff"
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"

      - name: "Compare PackageInfo.g with CITATION.cff"
        uses: stertooy/validate-citation-with-pkginfo@v1
